---
# tasks file for apache
- name: Install Apache
  yum:
    name: httpd
    state: present

- name: Copy index.html
  copy:
    src: index.html
    dest: /var/www/html/index.html

- name: Start apache service
  service:
    name: httpd
    state: started
    enabled: yes
