---
# tasks file for tomcat
- name: Install Java
  yum:
    name: java
    state: latest

- name: Download tomcat and unarchive
  unarchive:
    src: "{{ tomcat_url }}"
    dest: /usr/local/
    remote_src: True
    
- name: Start tomcat service
  shell: nohup /usr/local/{{ tomcat_pkg }}/bin/startup.sh

- name: Copy the config file
  copy: 
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: 
    - restart the server
